language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
deploy:
  provider: pypi
  username: ${PYPI_USERNAME}
  password: ${PYPI_PASSWORD}
  on:
    python: 3
    tags: true
    branch: master
