os: linux
language: python
python:
  - "3.7"
script: python setup.py sdist build
deploy:
  edge: true
  provider: pypi
  username: "__token__"
  password: ${PYPI_TOKEN}
  on:
    branch: master
    tags: true
